### ISSUE TITLE
Weird TypeError

### ISSUE THREAD

**Issue by v0dro** [minad/iruby#54]
I'm calling the `#to_matrix` method on a `Daru::DataFrame` in the browser and this is the error I got:

```

/home/sameer/.rvm/gems/ruby-2.1.0/gems/iruby-0.1.13/lib/iruby/formatter.rb:12:in `*': no implicit conversion from nil to integer (TypeError)
	from /home/sameer/.rvm/gems/ruby-2.1.0/gems/iruby-0.1.13/lib/iruby/formatter.rb:12:in `matrix'
	from /home/sameer/.rvm/gems/ruby-2.1.0/gems/iruby-0.1.13/lib/iruby/display.rb:185:in `block in <module:Registry>'
	from /home/sameer/.rvm/gems/ruby-2.1.0/gems/iruby-0.1.13/lib/iruby/display.rb:108:in `call'
	from /home/sameer/.rvm/gems/ruby-2.1.0/gems/iruby-0.1.13/lib/iruby/display.rb:108:in `render'
	from /home/sameer/.rvm/gems/ruby-2.1.0/gems/iruby-0.1.13/lib/iruby/display.rb:64:in `block in render'
	from /home/sameer/.rvm/gems/ruby-2.1.0/gems/iruby-0.1.13/lib/iruby/display.rb:63:in `each'
	from /home/sameer/.rvm/gems/ruby-2.1.0/gems/iruby-0.1.13/lib/iruby/display.rb:63:in `render'
	from /home/sameer/.rvm/gems/ruby-2.1.0/gems/iruby-0.1.13/lib/iruby/display.rb:24:in `display'
	from /home/sameer/.rvm/gems/ruby-2.1.0/gems/iruby-0.1.13/lib/iruby/kernel.rb:71:in `display'
	from /home/sameer/.rvm/gems/ruby-2.1.0/gems/iruby-0.1.13/lib/iruby/kernel.rb:130:in `execute_request'
	from /home/sameer/.rvm/gems/ruby-2.1.0/gems/iruby-0.1.13/lib/iruby/kernel.rb:62:in `run'
	from /home/sameer/.rvm/gems/ruby-2.1.0/gems/iruby-0.1.13/lib/iruby/command.rb:30:in `run_kernel'
	from /home/sameer/.rvm/gems/ruby-2.1.0/gems/iruby-0.1.13/lib/iruby/command.rb:16:in `run'
	from /home/sameer/.rvm/gems/ruby-2.1.0/gems/iruby-0.1.13/bin/iruby:6:in `<top (required)>'
	from /home/sameer/.rvm/gems/ruby-2.1.0/bin/iruby:23:in `load'
	from /home/sameer/.rvm/gems/ruby-2.1.0/bin/iruby:23:in `<main>'
	from /home/sameer/.rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `eval'
	from /home/sameer/.rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `<main>'
```

It works completely fine in pry or irb, but the same error occurs in the iruby console too.

Here is the code of the `#to_matrix` method:

``` ruby

    def to_matrix
      numerics_as_arrays = []
      each_vector do |vector|
        numerics_as_arrays << vector.to_a if(vector.type == :numeric)
      end

      Matrix.columns numerics_as_arrays
    end
```

[Here](https://github.com/v0dro/daru/blob/master/lib/daru/dataframe.rb#L572) is the link to the repo.

**Comment by minad** [comment]
Can you debug this? The formatter tries to multiply with nil, which raises this exception. For some reason the column_count of your matrix is nil.

**Comment by v0dro** [comment]
Sure I'll give it a shot.

**Comment by minad** [comment]
please reopen on SciRuby/iruby if this is still an issue.
